name: tota
version: 0.6.0
description: >-
  A simple and elegant framework for generating static sites.
  Great for personal websites, blogs, documentation, and more.
author: izolate <izolate@gmail.com>
homepage: https://github.com/tota-dart/tota
documentation: https://github.com/tota-dart/tota/blob/master/README.md
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  path: ^1.6.2
  front_matter: ^1.1.0
  markdown: ^2.0.3
  mustache: ^1.1.1
  slugify: ^1.0.0
  intl: ^0.15.8
  args: ^1.5.2
  cli_util: ^0.1.3+2
  meta: ^1.1.7
  http: ^0.12.0+2
  crypto: ^2.0.6
  pool: ^1.4.0
dev_dependencies:
  test: ^1.6.4
executables:
  tota: tota
